### ISSUE TITLE
Lock support

### ISSUE THREAD

**Issue by Carghaez** [troyready/git-lfs-s3#10]
I have read that you think the lock support on s3 buckets is useless, but being LFS mainly used to work with binary files, the use of the lock makes teamwork more immediate allowing individuals to know which files are modified by whom so to prevent any conflicts (i.e. I know that file X is locked by my colleague A, I wait for him to commit or release it before I can modify it myself).

I'd love to hear your opinion, because from my point of view, locking files in LFS is essential regardless of the storage platform

**Comment by troyready** [comment]
You're absolutely right @Carghaez -- that comment about not supporting locks was incorrect (I think I was conflating it with posix file locking).

Lock support is in place now.
