### ISSUE TITLE
default UserPoolId on deployment

### ISSUE THREAD

**Issue by Carghaez** [troyready/git-lfs-s3#32]
Hello Troy! Here I am again.

I am writing this issue to know if it is possible to implement, with relatively little effort, a --user-pool-id parameter to be passed to the deploy command to use an existing UserPool instead of creating a new one every time.

This kind of behaviour is useful when you want to manage a project with different sub-repo that refer to different storage/buckets but have the same userbase.

Stay safe!

**Comment by troyready** [comment]
I don't believe Serverless Framework has a particularly convenient way to do this (associate CLI parameters with variables or CFN parameters.

I concede that it's annoying to have to copy & modify the project to achieve this and am open to ideas to make it more flexible.
