### ISSUE TITLE
Error 413

### ISSUE THREAD

**Issue by marcelinhov2** [troyready/git-lfs-s3#52]
Hey, first of all thanks for the solution. :)

I'm trying to do an implementation using that, I prepared everything and also removed all the auth piece (in order to test the failure I'm getting)

The point is that when I try to push a 5mb file to code commit, after implement everything you shared, I'm getting a 413 error.
![image](https://github.com/troyready/git-lfs-s3/assets/232648/39ee1ed9-36e4-482b-a1bb-dd39f712201a)

After some research, I see the problem is related to pushing big files. Do you already faced it?
Maybe you can point me to the right direction here.

Thanks for the help 🙏 .

**Comment by troyready** [comment]
That's an interesting one @marcelinhov2 , I haven't run into anything like it. There definitely isn't an architectural issue with sending a 5mb (or much larger) - the Lambda functions don't see any of the files, just a hash.

What loggroup/function is that error from? None of the functions should be getting any particularly large requests.

I just ran a quick test from scratch to make sure nothing new was amiss:

```bash
npm ci
npx sls deploy -s troytest -r us-west-2 --verbose
aws cognito-idp admin-create-user --user-pool-id us-west-2_jIYHdGO5j --username tready --user-attributes Name=email,Value=troy@example.com Name=phone_number,Value="+12135551212" --message-action SUPPRESS --region us-west-2
aws cognito-idp admin-set-user-password --user-pool-id us-west-2_jIYHdGO5j --username tready --password Testpass@111 --permanent --region us-west-2
aws codecommit create-repository --repository-name testgitlfs --region us-west-2
# repo & LFS in place, now testing them
 cd $(mktemp -d)
 CC_REPO_URL=https://git-codecommit.us-west-2.amazonaws.com/v1/repos/testgitlfs
git init
git config credential."$CC_REPO_URL".helper '!aws codecommit credential-helper $@'
git config credential."$CC_REPO_URL".UseHttpPath true
git remote add origin $CC_REPO_URL

truncate -s 20M test.dat
git lfs track "*.dat"
git config -f .lfsconfig remote.origin.lfsurl https://eubor6lku0.execute-api.us-west-2.amazonaws.com/troytest
git add .gitattributes .lfsconfig test.dat
git commit -m "initial commit"
git push -u origin main
```

The push output looks like:
```
Username for 'https://eubor6lku0.execute-api.us-west-2.amazonaws.com': tready
Password for 'https://tready@eubor6lku0.execute-api.us-west-2.amazonaws.com': 
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.https://eubor6lku0.execute-api.us-west-2.amazonaws.com/troytest.locksverify true
Uploading LFS objects: 100% (1/1), 21 MB | 3.8 MB/s, done.                                                                                        
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 20 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 531 bytes | 531.00 KiB/s, done.
Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
remote: Validating objects: 100%
To https://git-codecommit.us-west-2.amazonaws.com/v1/repos/testgitlfs
 * [new branch]      main -> main
branch 'main' set up to track 'origin/main'.
```

The LFS elements of the git config should look something like this:
```
$ cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[credential "https://git-codecommit.us-west-2.amazonaws.com/v1/repos/testgitlfs"]
	helper = !aws codecommit credential-helper $@
	UseHttpPath = true
[remote "origin"]
	url = https://git-codecommit.us-west-2.amazonaws.com/v1/repos/testgitlfs
	fetch = +refs/heads/*:refs/remotes/origin/*
[lfs]
	repositoryformatversion = 0
[lfs "https://eubor6lku0.execute-api.us-west-2.amazonaws.com/troytest"]
	access = basic
[branch "main"]
	remote = origin
	merge = refs/heads/main

$ cat .lfsconfig 
[remote "origin"]
	lfsurl = https://eubor6lku0.execute-api.us-west-2.amazonaws.com/troytest
```

If nothing stands out as being particularly different, increasing git verbosity (e.g. `GIT_CURL_VERBOSE=1 GIT_TRACE=1 `) when pushing might give info pointing to where the issue is.

**Comment by marcelinhov2** [comment]
Thanks @troyready , I'll try.

The log group I'm showing you is from a lambda that is triggered when a file is dropped in a specific S3 bucket. So my lambda get this file content and try to push to code commit.
![image](https://github.com/troyready/git-lfs-s3/assets/232648/b6719903-62ab-446b-9f18-65a5444de347)

The message is from here.

**Comment by troyready** [comment]
Ah, I see.

The primary issue here is that CodeCommit (or whatever other repo you'd be using) doesn't store the actual content of the large files, but instead replaces them [with a text pointer](https://github.com/git-lfs/git-lfs/blob/v3.3.0/docs/spec.md#the-pointer) as the file in the repo. When a git-lfs enabled git client then receives the file (e.g. during a clone), it reaches out to the git-lfs server (what this project provides) and swaps the file in the working tree with the real large one.

So for your design, a couple of thoughts:

* If you have control over the file uploads as well, I'd see about [switching them to hash in sha256](https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/). Then your function handler ^ wouldn't need to getObject on the new file as the hash should already be in the event or available via s3:GetObjectAttributes

* The file commited to codecommit would look something like (I haven't tested this):

```typescript
import { createHash } from 'node:crypto'

const fileContent = `version https://git-lfs.github.com/spec/v1
oid sha256:${s3Object.Body}
size ${record.s3.object.size}

```

**Comment by troyready** [comment]
My original comment above was sent early on accident; updated now.

**Comment by marcelinhov2** [comment]
@troyready sorry for keep doing questions for you. I was made to advance, my file was commited but I still have a few doubts:
1 - When I made my first commit, the 2 lfs config files I had there in codeCommit was gone. I'm not sure if it should be this way
2 - I see my file here:
![image](https://github.com/troyready/git-lfs-s3/assets/232648/aa963240-28ff-4b0b-b176-68323abbeeb5)
![image](https://github.com/troyready/git-lfs-s3/assets/232648/6211a7d9-a720-47a9-9538-036e69528931)
but when I access the logs of your service or even the uploadBucket, nothing is there. So I'm really not sure if it worked. For now, I have no authentication, it's all open, because I'm doing some tests.
3 - The lambda output from the code you shared is here:
![image](https://github.com/troyready/git-lfs-s3/assets/232648/f11af5fd-5892-4091-9fd8-a5c9e77424ef)

Thanks for your help.

**Comment by troyready** [comment]
1) I don't have any advice about the missing lfsattributes file in the repo; maybe the commit with it wasn't pushed?

2) The thing you're trying to do is to implement the git-lfs client in Lambda. To do that would look something like:

* Receive the S3 notification
* Call the git-lfs server [batch API](https://github.com/git-lfs/git-lfs/blob/main/docs/api/batch.md) (e.g. a node-fetch to `https://yourapi.execute-api.region.amazonaws.com/stage/objects/batch`) requesting an upload of the new object.
* It will respond with a pre-signed S3 URL to which you upload the file
* Then you commit the pointer file in the repo. The output from my example looks mostly correct, just needs to drop the extra 4 spaces at the start of lines 2 &3)

**Comment by marcelinhov2** [comment]
Hey @troyready , thanks for all the help. Apparently it worked.

I didn't understood this part
`Then you commit the pointer file in the repo. The output from my example looks mostly correct, just needs to drop the extra 4 spaces at the start of lines 2 &3)`

Maybe I'm still missing something here.

**Comment by troyready** [comment]
I mean that the repo file contents should look like this instead:

```
const fileContent = `version https://git-lfs.github.com/spec/v1\noid:sha256:${createHash('sha256').update(s3Object.Body).digest('hex')}\nsize ${record.s3.object.size}\n`
```

(no extra spaces before oid & size)

**Comment by marcelinhov2** [comment]
I'm having some problem, I didn't identified. but I'm moving forward lol. Now everything seems to be working, except when I try to pull the big files (stored in S3) with the git lfs fetch or git pull command, but It don't download the files. something is wrong from my side yet :(

**Comment by troyready** [comment]
For the client to substitute the files properly (replacing the text pointer files stored in the repo with the actual large file in the working tree) you need:

* [Git LFS installed & initialized](https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage) on the client system
* The client's repo settings configured for the appropriate filenames. You can see that happening in my [example here](https://github.com/troyready/git-lfs-s3/issues/52#issuecomment-1540504358), where `git lfs track` is creating the `.gitattributes` & `.lfsconfig` files and modifying the `.git/config` to specify the git lfs server

**Comment by marcelinhov2** [comment]
Yeah, I didn't made the .git/config piece. going to work on that and try to make it work.

Also a good point, I'm using AWS_IAM as the authorizer instead of Cognito. As my lambda has all the roles set, API Gateway enables the request and do the commit. all the main flow is working, now it's a matter of make this link between the pointer and the file correct.

Thank you very much for all your help here.

**Comment by troyready** [comment]
My pleasure!
