### ISSUE TITLE
Can this be used to store just some files in AWS S3?

### ISSUE THREAD

**Issue by cprince-foreflight** [troyready/git-lfs-s3#62]
In our project we're currently using Github support for Git LFS to store files. Is it possible to use your setup to use Git LFS for just some of our files? i.e., to keep the current Git LFS files where they are.

**Comment by troyready** [comment]
I think it would be possible, but would require a significant amount of customization.

If you configured your repos to point to this API as the LFS server, this "server's" functions could in turn interact with the GitHub LFS api to determine if the requested blobs were in GitHub LFS storage and if so return links to them.
